baseURL = "/"
relativeurls = true
languageCode = "ja"
hasCJKLanguage = true
title = "TypeError:"
theme = "hugo-kiera"

[author]
    name = "zinrai"
    github = "zinrai"
    twitter = "zinrai"

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags"
  weight = 1
